return {
  "nvim-treesitter/nvim-treesitter",
  branch = "main",
  build = ":TSUpdate",
  lazy = false,
  config = function()
    require("nvim-treesitter").install({
      "bash",
      "c",
      "diff",
      "html",
      "json",
      "latex",
      "lua",
      "luadoc",
      "make",
      "markdown",
      "markdown_inline",
      "python",
      "ron",
      "rust",
      "toml",
      "typst",
      "vim",
      "vimdoc",
      "wgsl",
      "yaml",
    })
  end,
}
