vim.g.mapleader = " "
vim.g.maplocalleader = " "

require("options")
require("globals")
require("aucommands")
require("commands")
require("languages")
require("mason-nvim")
require("mappings")
require("editor")
require("oil-nvim")
require("search")
require("completion")
require("lsp")
require("linting")
require("formatting")
require("diagnostic")
require("testing")
require("debugger")
require("theme")
require("statusline")
